services:
  coophub:
    build:
      context: .docker/coophub
      args:
        version_elixir: ${VERSION_ELIXIR:-1.14}
        host_uid: ${UID:-1000}
        host_gid: ${GID:-1000}
    ports:
      - 127.0.0.1:4000:4000
    volumes:
      - ./:/coophub
      - ~/.mix:/root/.mix/
      - ~/.npm:/root/.npm/
    environment:
      - GITHUB_OAUTH_TOKEN

  nodejs:
    image: node:${VERSION_NODE:-18}
    working_dir: "/coophub"
    volumes:
      - ./:/coophub
      - ~/.npm:/root/.npm/
    command: bash -c "sh .docker/nodejs/entrypoint.sh"