services:
  coophub:
    build:
      context: .docker/coophub
      args:
        version_elixir: ${VERSION_ELIXIR:-1.14}
        version_node: ${VERSION_NODE:-16}
        host_uid: ${UID:-1000}
        host_gid: ${GID:-1000}
    ports:
      - 127.0.0.1:4000:4000
    volumes:
      - ./:/coophub
      - ~/.mix:/root/.mix/
      - ~/.npm:/root/.npm/
    environment:
      - VERSION_COOPHUB=${VERSION_COOPHUB:-master}
      - GITHUB_OAUTH_TOKEN
